Fix tests due to os.path.basename() failures on Python 3.6.
This commit fixes the following Python 3.6 errors when running tests:

    TypeError: expected str, bytes or os.PathLike object, not MagicMock

In Python 3.6, os.path.basename() no longer accepts a mock. We need to mock it
so it does not fail.